### ISSUE TITLE
Number of iterations of LBFGS

### ISSUE THREAD

**Issue by una-dinosauria** [hellozting/CompositeQuantization#10]
Hi!

Running this code, I see that the number of LBFGS iterations goes up to 700, which makes updating the codebook the most expensive part of the algorithm by far.

In the paper, the following is written:

![image](https://user-images.githubusercontent.com/3733964/39530446-fccff7f8-4df6-11e8-9b0c-2a54d62d77aa.png)

I see that you have set the number of line searches to 5

https://github.com/hellozting/CompositeQuantization/blob/1c7fdcdda224698dbc55a176afd517dad4e0bfcc/ReleaseVersion/CompositeQuantization.cpp#L150-L154

But I cannot find a line setting the maximum number of iterations to 10.
Is this something that is missing from the code?

Cheers,

**Comment by una-dinosauria** [comment]
Oh, my bad. Apparently `m` is the number of iterations used to approximate the Hessian: https://github.com/hellozting/CompositeQuantization/blob/1c7fdcdda224698dbc55a176afd517dad4e0bfcc/ReleaseVersion/lbfgs.h#L199-L207

The other parameters are `max_iteration`, which would be T_c in the paper:
https://github.com/hellozting/CompositeQuantization/blob/1c7fdcdda224698dbc55a176afd517dad4e0bfcc/ReleaseVersion/lbfgs.h#L240-L248
but defaults to zero and thus continues for a long long time.

and `max_linesearch`
https://github.com/hellozting/CompositeQuantization/blob/1c7fdcdda224698dbc55a176afd517dad4e0bfcc/ReleaseVersion/lbfgs.h#L257-L262
which defaults to 20 (not 5, as the paper says).

**Comment by una-dinosauria** [comment]
cc @welleast?

**Comment by hellozting** [comment]
Hi, 

Sorry about the misinformation. We intended to say “10 in average in our implementation”, and the nubmer 10 is estimated from the experiment on 1MGIST with 32 bits. I calculated the exact averaged number of LBFGS iterations for updatng dictionaries, and they are 18, 45, 64 on 1MGIST with 32 bits, 64 bits, 128 bits respectiely and 24, 44, 64 on 1MSIFT with 32 bits, 64 bits, 128 bits.

It's true that the number of LBFGS iterations can goes up to hundreds, yet this only appears in early iterations. Updating dictionaries at later iterations takes much less time than that at early iterations because the LBFGS algorithm adaptively adjusts the number of inner iterations. For example, on 1MGIST with 64 bits, the runtime cost of updating dictionary is 1220s for the first iteration and 680s for the second iteration and then becomes about 190s for the last ten iterations.  The averaged runtime costs for each iteration for the tree steps, updating the binary codes, updating epsilon, and updating the dictionaries are 29.5s, 0.02s, 61.8s on 1MSIFT with 64 bits and 197s, 0.02s, 392s on 1MGIST with 64 bits. The costs are evaluated on a Windows Server with 256GB RAM, 24 cores with each running 2.30GHZIntel Xeon processor. 

You are right that the number of linear seaches should be 20 in our implementation. Sorry again about the misinformation. 

We will clarify this and report the runtime cost in our journal version.

Thanks!

**Comment by hellozting** [comment]
Hi, 

Sorry about the misinformation. We intended to say “10 in average in our implementation”, and the number 10 is estimated from the experiment on 1MGIST with 32 bits. I calculated the exact averaged number of LBFGS iterations for updatng dictionaries, and they are 18, 45, 64 on 1MGIST with 32 bits, 64 bits, 128 bits respectively and 24, 44, 64 on 1MSIFT with 32 bits, 64 bits, 128 bits. 

It's true that the number of LBFGS iterations can goes up to hundreds, yet this only appears in early iterations. Updating dictionaries at later iterations takes much less time than that at early iterations because the LBFGS algorithm adaptively adjusts the number of inner iterations. For example, on 1MGIST with 64 bits, the runtime cost of updating dictionary is 1220s for the first iteration and 680s for the second iteration and then becomes about 190s for the last ten iterations.  The averaged runtime costs for each iteration for the tree steps, updating the binary codes, updating epsilon, and updating the dictionaries are 29.5s, 0.02s, 61.8s on 1MSIFT with 64 bits and 197s, 0.02s, 392s on 1MGIST with 64 bits. The costs are evaluated on a Windows Server with 256GB RAM, 24 cores with each running 2.30GHZ Intel Xeon processor. 

You are right that the number of line seaches should be 20 in our implementation. Sorry again about the misinformation. 

We will clarify this and report the runtime cost in our journal version.
 
Thanks!
